services:
  bulb-api:
    image: ghcr.io/ianfebi01/bulb-api:latest
    container_name: bulb-api
    volumes:
      - bulb-data:/app/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  bulb-data:
